### ISSUE TITLE
Rip out DefDoc

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jphmrst/cl-nst#4]
```
Interesting experiment; time to be rid of it.
```

Original issue reported on code.google.com by `john.mar...@gmail.com` on 2 Sep 2014 at 4:04

**Comment by jphmrst** [comment]
DefDoc is gone; about half way through getting documentation via [CL-org-sampler](https://github.com/jphmrst/cl-org-sampler) going.

**Comment by jphmrst** [comment]
Fully replaced in 4.1.0.
